### ISSUE TITLE
Little X's don't work on Chrome

### ISSUE THREAD

**Issue by vortexing** [FredHutch/batch-dashboard#16] opened 2019-05-13 16:08 UTC
![Screen Shot 2019-05-13 at 9 07 35 AM](https://user-images.githubusercontent.com/13182518/57636766-ac52e480-755e-11e9-94cf-f2191796cd66.png)
In these little info boxes, you have to scroll down and hit close (which is fine), but the little X's at the top don't seem to work to close the boxes.   

Just FYI. ;)

**Comment by dtenenba** [comment] 2020-05-07 00:38
Not a fix, but you can also click outside the dialog box to make it go away.

**Comment by dtenenba** [comment] 2020-05-07 00:39
duplicate of #6

**Closed by dtenenba** 2020-05-07 00:39 UTC
